"""Generate GRAPHICS_HOME_* constants from rom/forth_boot.asm's own
GRAPHICS_HOME_TABLE, so rom/graphics_exrom.asm never hand-copies that
table's layout again.

Modeled on the sibling structured-basic-poc project's own tools/
export_home_symbols.py (cited in rom/graphics_exrom.asm's own header as
the proven precedent this project didn't yet have), adapted to this
project's actual mechanism: GRAPHICS_HOME_TABLE is a FIXED, append-only
table of `jp TARGET` veneers at a fixed low address ($0100), not a set
of real, independently-moving Home ROM symbol addresses -- so unlike
structured-basic-poc's own version, this reads rom/forth_boot.asm's
SOURCE directly (the table's own slot order is everything that
matters; the real GFX_* addresses those slots jump to are free to move
every time the dictionary changes without affecting this at all), not
a post-build .sym file.

Each generated constant's address is $0100 + 3*slot_index (each veneer
is exactly one 3-byte `jp nn`), and its name is GRAPHICS_HOME_<TARGET>
with any leading GFX_ stripped from the jump target -- exactly the
naming convention rom/graphics_exrom.asm's own (formerly hand-typed)
constants already used, so this is a drop-in replacement, not a rename.

Usage: export_home_symbols.py FORTH_BOOT.asm OUTPUT.inc
"""
import re
import sys
from pathlib import Path

TABLE_LABEL = "GRAPHICS_HOME_TABLE"
TABLE_BASE = 0x0100
SLOT_SIZE = 3


def parse_table(source: str):
    lines = source.splitlines()
    try:
        start = next(i for i, line in enumerate(lines)
                      if line.strip() == f"{TABLE_LABEL}:")
    except StopIteration:
        raise SystemExit(f"{TABLE_LABEL}: label not found")

    # The fixed-$0100 assumption depends on a `DS $0100 - $, $FF` pad
    # immediately preceding the table (blank/comment lines allowed in
    # between) -- refuse to generate wrong constants silently if a
    # future edit ever removes or moves that pad.
    preceding = "\n".join(lines[max(0, start - 15):start])
    if not re.search(r"DS\s+\$0100\s*-\s*\$,\s*\$FF", preceding):
        raise SystemExit(
            f"{TABLE_LABEL}: no 'DS $0100 - $, $FF' pad found immediately "
            "before it -- refusing to assume it still starts at $0100")

    targets = []
    for line in lines[start + 1:]:
        stripped = line.strip()
        if not stripped:
            continue
        m = re.match(r"^jp\s+([A-Za-z_][A-Za-z0-9_]*)", stripped)
        if m:
            targets.append(m.group(1))
            continue
        # a continuation comment line for the previous jp (this
        # project wraps long slot comments onto their own line) -- skip
        if stripped.startswith(";"):
            continue
        break  # first non-jp, non-comment line ends the table

    if not targets:
        raise SystemExit(f"{TABLE_LABEL}: no `jp TARGET` veneers found")
    return targets


def constant_name(target: str) -> str:
    suffix = target[4:] if target.startswith("GFX_") else target
    return f"GRAPHICS_HOME_{suffix}"


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: export_home_symbols.py FORTH_BOOT.asm OUTPUT.inc")
    source_path, output_path = map(Path, sys.argv[1:])
    targets = parse_table(source_path.read_text())

    lines = [
        "; Generated by tools/export_home_symbols.py from "
        f"{source_path.as_posix()}'s own",
        f"; {TABLE_LABEL} -- do not edit by hand, and do not hand-copy",
        "; these constants back into rom/graphics_exrom.asm; INCLUDE this",
        "; file instead. Regenerate whenever that table's own slot order",
        "; changes (appending a new slot at the end is always safe;",
        "; reordering or removing an existing slot is not -- see that",
        "; table's own header).",
    ]
    for i, target in enumerate(targets):
        addr = TABLE_BASE + i * SLOT_SIZE
        lines.append(
            f"{constant_name(target)} EQU ${addr:04X}   ; slot {i} -- {target}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    print(f"export_home_symbols: wrote {output_path} ({len(targets)} slots)")


if __name__ == "__main__":
    main()
